# nvim config
.config/nvim:
  type: git-repo
  url: https://github.com/stanly0726/nvim.git
  clone:
    args: ['--branch','colemak']

# tmux plugin manager
.tmux/plugins/tpm:
  type: git-repo
  url: https://github.com/tmux-plugins/tpm.git

# fzf
.fzf:
  type: git-repo
  url: https://github.com/junegunn/fzf.git
  clone:
    args: ['--depth', '1']

{{ if eq .cargo_package "download" }}
# rm alternative
.local/bin/rip:
  type: file
  url: https://github.com/nivekuil/rip/releases/download/0.12.0/rip
  executable: true

# ls alternative
.local/bin/eza:
  type: archive-file
  url: https://github.com/eza-community/eza/releases/download/v0.16.1/eza_x86_64-unknown-linux-gnu.tar.gz
  executable: true
  path: ./eza
{{ end }}
