set -g @plugin 'vaaleyard/tmux-dotbar'

set -g @tmux-dotbar-window-status-format ' #I #W '
set -g @tmux-dotbar-right true

# Ghostty Default Style Dark
# set -g @tmux-dotbar-bg "#282c34"
# set -g @tmux-dotbar-fg "#666666"
# set -g @tmux-dotbar-fg-current "#eaeaea"
# set -g @tmux-dotbar-fg-session "#82a2be"
# set -g @tmux-dotbar-fg-prefix "#b294bb"

# Everforest Dark Hard
set -g @tmux-dotbar-bg "#272e33"
set -g @tmux-dotbar-fg "#7a8478"
set -g @tmux-dotbar-fg-current "#d3c6aa"
set -g @tmux-dotbar-fg-session "#7fbbb3"
set -g @tmux-dotbar-fg-prefix "#d699b6"
