[window]
padding = { x = 5, y = 12 }
dynamic_padding = true
opacity = 0.95

[font]
size = 12.0

[font.normal]
family = "Iosevka Term Extended"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NF"
style = "Italic"

[general]
# import = ["~/.config/alacritty/themes/themes/nordfox.toml"]
import = ["~/.config/alacritty/themes/themes/ghostty_default_styledark.toml"]

